### ISSUE TITLE
rustdesk.install has failed automated package testing

### ISSUE THREAD

**Issue by jkirk** [bdukes/Chocolatey-Packages#70]
I finally took some time to investigate the "rustdesk.install has failed automated package testing (verification)" problem.

Only after I have set up the Vagrant [Chocolatey Testing Environment](https://github.com/chocolatey-community/chocolatey-test-environment) I found that @virtualex-itv + @bdukes are already working on this:

* https://github.com/bdukes/Chocolatey-Packages/issues/62
* https://github.com/bdukes/Chocolatey-Packages/pull/63
* https://github.com/bdukes/Chocolatey-Packages/pull/64
* https://github.com/bdukes/Chocolatey-Packages/pull/66
* https://github.com/bdukes/Chocolatey-Packages/pull/67
* https://github.com/bdukes/Chocolatey-Packages/pull/68
* https://github.com/bdukes/Chocolatey-Packages/pull/69

FTR:

* Changes so far: https://github.com/bdukes/Chocolatey-Packages/compare/26867fd9392df1bee5ef0a86894dfb7e2ee95e2d...HEAD
* Azure Pipline (bdukes.Chocolatey-Packages): https://dev.azure.com/dukesb11/Chocolatey-Packages/_build?definitionId=1

So my efforts on this issue might be not be needed any more, but I thought I'd still share my findings.
Please close this issue, once the the package got accepted in Chocolatey.

The problem: RustDesk (Install) > 1.2.6 (up to currently 1.3.9) were in "[moderation](https://community.chocolatey.org/packages/rustdesk.install/1.3.9#versionhistory)" because "rustdesk.install has failed automated package testing (verification)".
The chocolatey-ops (reviewer) bot reported:

> rustdesk.install has failed automated package testing (verification).
> Please visit https://gist.github.com/choco-bot/c011ef7d56f69c642023b739e399f7dd for details.
> The package status will be changed and will be waiting on your next actions.
> 
>    NEW! We have a [test environment](https://github.com/chocolatey-community/chocolatey-test-environment) for you to replicate the testing we do. This can be used at any time to test packages! See https://github.com/chocolatey-community/chocolatey-test-environment
>  [...]

My environment is Debian/bookworm and I was running the following versions of Vagrant + VirtualBox + Vagrant Plugins:

```
❯ dpkg -l | grep " vagrant"
ii  vagrant                                          2.3.4+dfsg-1+deb12u1                   all          Tool for building and distributing virtualized development environments
❯ dpkg -l | grep virtualbox
ii  virtualbox-7.0                                   7.0.26-168464~Debian~bookworm          amd64        Oracle VM VirtualBox
❯ vagrant plugin install winrm winrm-fs
❯ vagrant plugin install winrm-elevated
❯ vagrant plugin list                  
winrm (2.3.9, global)
  - Version Constraint: > 0
winrm-elevated (1.2.3, global)
winrm-fs (1.3.5, global)
  - Version Constraint: > 0
```

I cloned Chocolatey Testing Environment + prepared the Vagrant box:

```
❯ git clone https://github.com/chocolatey-community/chocolatey-test-environment.git
❯ vagrant up
❯ vagrant snapshot save good
```

I updated the `Vagrantfile` and tested RustDesk 1.3.9:
```
❯ git diff Vagrantfile        
diff --git a/Vagrantfile b/Vagrantfile
index 9cea128..6810613 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -141,7 +141,7 @@ Write-Output "Testing package if a line is uncommented."
 # THIS IS WHAT YOU CHANGE
 # - uncomment one of the two and edit it appropriately
 # - See the README for details
-#choco.exe install -fdvy INSERT_NAME --version INSERT_VERSION  --allow-downgrade
+choco.exe install -fdvy rustdesk.install --version 1.3.9 --allow-downgrade
 #choco.exe install -fdvy INSERT_NAME  --allow-downgrade --source "'c:\\packages;http://chocolatey.org/api/v2/'"
❯ vagrant provision
```

I also tested RustDesk 1.4.0 and can report that both versions were installed successfully.
See the logs:

[vagrant-provision-rustdesk-1.3.9.log](https://github.com/user-attachments/files/20431464/vagrant-provision-rustdesk-1.3.9.log)

[vagrant-provision-rustdesk-1.4.0.log](https://github.com/user-attachments/files/20431465/vagrant-provision-rustdesk-1.4.0.log)

So I compared the output of the log with the given [Install.txt](https://gist.github.com/choco-bot/c011ef7d56f69c642023b739e399f7dd#file-install-txt) of the Gist link

```
❯ tail -50 vagrant-provision-rustdesk-1.3.9.log 
    default: Verifying package provided checksum of 'c79168f5ae10663b72fb80390098dc498bdaae67d45b2e9796193ee073030b27' for 'C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi'.
    default: Running Get-ChecksumValid -file 'C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi' -checksum 'c79168f5ae10663b72fb80390098dc498bdaae67d45b2e9796193ee073030b27' -checksumType 'sha256' -originalUrl 'https://github.com/rustdesk/rustdesk/releases/download/1.3.9/rustdesk-1.3.9-x86_64.msi'
    default: checksum.exe found at 'C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
    default: Executing command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="c79168f5ae10663b72fb80390098dc498bdaae67d45b2e9796193ee073030b27" -t="sha256" -f="C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi"]
    default: Hashes match.
    default: Command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="c79168f5ae10663b72fb80390098dc498bdaae67d45b2e9796193ee073030b27" -t="sha256" -f="C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi"] exited with '0'.
    default: Running Install-ChocolateyInstallPackage -packageName 'rustdesk.install' -fileType 'msi' -silentArgs '/q /norestart' -file 'C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi' -validExitCodes '0' -useOnlyPackageSilentArguments 'False'
    default: Running Get-OSArchitectureWidth -compare '32'
    default: Installing rustdesk.install...
    default: Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -workingDirectory 'C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9' -statements '/i "C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi" /q /norestart' -exeToRun 'C:\Windows\System32\msiexec.exe'
    default: Running Test-ProcessAdminRights
    default: Test-ProcessAdminRights: returning True
    default: Finishing 'Test-ProcessAdminRights'
    default: Elevating permissions and running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi" /q /norestart]. This may take a while, depending on the statements.
    default: Command ["C:\Windows\System32\msiexec.exe" /i "C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.msi" /q /norestart] exited with '0'.
    default: Finishing 'Start-ChocolateyProcessAsAdmin'
    default: rustdesk.install has been installed.
    default: ----------------------------------------------------------------------
    default: Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = '';[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::SystemDefault; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\rustdesk.install\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null'] exited with '0'.
    default: Calling command ['"C:\Windows\System32\shutdown.exe" /a']
    default: Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'
    default:   rustdesk.install can be automatically uninstalled.
    default: Capturing package files in 'C:\ProgramData\chocolatey\lib\rustdesk.install'
    default:  Found 'C:\ProgramData\chocolatey\lib\rustdesk.install\rustdesk.install.nupkg'
    default:   with checksum '696756800443C93C2C562ADA2A45D672'
    default:  Found 'C:\ProgramData\chocolatey\lib\rustdesk.install\rustdesk.install.nuspec'
    default:   with checksum '6016826CE5ABF9BE592420EEEFFA7882'
    default:  Found 'C:\ProgramData\chocolatey\lib\rustdesk.install\tools\chocolateyBeforeModify.ps1'
    default:   with checksum 'B50FFF47613C3C4EDE784880ADBDE14C'
    default:  Found 'C:\ProgramData\chocolatey\lib\rustdesk.install\tools\chocolateyInstall.ps1'
    default:   with checksum '6EA87BB55B90C01E31EEA8BC6A8BB683'
    default:  Found 'C:\ProgramData\chocolatey\lib\rustdesk.install\tools\chocolateyUninstall.ps1'
    default:   with checksum 'BD4396402D423F652E560D1FBC3F1B7E'
    default: Attempting to create directory "C:\ProgramData\chocolatey\.chocolatey\rustdesk.install.1.3.9".
    default: There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\rustdesk.install.1.3.9\.registry'
    default: There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\rustdesk.install.1.3.9\.files'
    default: Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\rustdesk.install.1.3.9\.extra".
    default: Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\rustdesk.install.1.3.9\.version".
    default: Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\rustdesk.install.1.3.9\.sxs".
    default: Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\rustdesk.install.1.3.9\.pin".
    default: Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
    default: Attempting to delete file "C:\ProgramData\chocolatey\lib\rustdesk.install\.chocolateyPending".
    default:  The install of rustdesk.install was successful.
    default:   Deployed to 'C:\Program Files\RustDesk\'
    default:
    default: Chocolatey installed 1/1 packages.
    default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    default: Sending message 'PostRunMessage' out if there are subscribers...
    default: Exiting with 0
    default: Exit code was 0
```

The significant difference can be seen in the [lines 520 - 521](https://gist.github.com/choco-bot/c011ef7d56f69c642023b739e399f7dd#file-install-txt-L520):
```
2025-05-16 18:41:25,055 4672 [DEBUG] - Elevating permissions and running ["C:\Users\vagrant\AppData\Local\Temp\chocolatey\rustdesk.install\1.3.9\rustdesk-1.3.9-x86_64.exe" --silent-install]. This may take a while, depending on the statements.
2025-05-16 19:25:53,502 4672 [WARN ] - Chocolatey timed out waiting for the command to finish. The timeout
 specified (or the default value) was '2700' seconds. Perhaps try a
 higher `--execution-timeout`? See `choco -h` for details.
```

So the installation time outs after more than 40 minutes. It is unclear why. It works in the Test Environment.
We could investigate this, if we want to. But it seems, the change from the EXE to the MSI installer seems to have solved it.
